server.port: 1234

jira:
  username: <username_value>
  password: <pswd_value>
  url: <jira_url_value>
  project: <project_value>
  ciUserName: <ci_user_name>

data:
  namespaces:
    - my_namespace
  environments:
    - dev


logging.level.by.sb.jirahelper: DEBUG